---
name: Validate pull request
on:
    pull_request:
        branches:
            - main
            - beta
            - alpha
            - dev
jobs:
    check-style:
        name: Check code style
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: temurin
                  cache: gradle
            - name: Perform style check
              run: ./gradlew ktlintCheck
    build-and-test:
        name: Build and test project
        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest
                distribution:
                    - temurin
                    - zulu
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: ${{ matrix.distribution }}
                  cache: gradle
            - name: Perform build and tests
              run: ./gradlew clean build
